---
title: "p8105_hw2_ar4173"
author: "Anand Rajan"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("readxl")
library(tidyr)
```

## Problem 1

Data Import and Cleaning of Trash Wheel Dataset

```{r}
trashwheel_data = 
read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel") %>% 
janitor::clean_names() %>% 
select(-x15, -x16,-x17) %>% 
drop_na() %>% 
mutate(across(c(sports_balls), ~ round(., 0)))

trashwheel_data
```


Cleaning and Combining Precipitation data from 2018 and 2019


```{r}
prcp2018_data =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 5, range="A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year="2018")

prcp2019_data =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 4, range="A2:B15") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year="2019")

prcp_data = 
  left_join(prcp2018_data, prcp2019_data, by="month") %>% 
  mutate(month=month.name[])
  
```


```{r eval=FALSE}
The trash wheel data set 
```

## Problem 2

Cleaning and Joining Datasets

```{r}
pols_data =
  read_csv(file= "./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(col = "mon",into= c("year","month","day"), sep ="-", remove = TRUE, convert = TRUE, extra = 'warn',fill='warn') %>%
  mutate(
    month= month.abb[month],
    president = recode(prez_gop, '1' = "gop", "0"="dem")
    ) %>% 
  select(-day, -prez_gop, -prez_dem)

```

Clean snp dataset

```{r}
snp_data =
  read_csv(file = "./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  mutate(lubridate::mdy(date)) %>% 
  separate(col = "lubridate::mdy(date)",into = c("year","month","day"), sep = "-", remove = TRUE, convert = TRUE, extra = 'warn',fill='warn') %>%
  mutate(
    month= month.abb[month],
    year= if_else(year>2021, year-100, as.numeric(year))) %>% 
  select(-day, -date) %>% 
  relocate(year,month,close)
```

clean unemployment dataset

```{r}
unemployment_data =
  read_csv(file= "./data/unemployment.csv")


unemployment_tidy_data= 
  pivot_longer(
    unemployment_data,
    Jan:Dec,
    names_to= "month",
    values_to = "Percentage of Unemployment"
  )
```

Joining the Datasets

```{r}
temp_join =
  inner_join(snp_data,pols_data, by=c("year"="year","month"="month"))

poltics_success=
  inner_join(temp_join,unemployment_tidy_data,by=c("year"="Year","month"="month") )
```

#Problem 3

Import and Tidy Baby Names dataset
```{r}
babynames =
  read_csv(file="./data/Popular_Baby_names.csv") %>%
  janitor::clean_names() %>%
  distinct(year_of_birth,ethnicity,childs_first_name,.keep_all=TRUE) %>% 
  mutate(
    ethnicity = replace(ethnicity, ethnicity=="BLACK NON HISP", "BLACK NON HISPANIC"),
    ethnicity = replace(ethnicity, ethnicity=="WHITE NON HISP", "WHITE NON HISPANIC"),
    ethnicity = replace(ethnicity, ethnicity=="ASIAN AND PACI", "ASIAN AND PACIFIC ISLANDER")
    )
  
```


```{r}
olivia_df = pivot_wider(
  babynames,
  names_from = year_of_birth,
  values_from = rank
) %>% 
  filter(childs_first_name == "Olivia") %>% 



```


Table displaying P

```{r}
male_df =
  filter(
  babynames,
  rank=="1",
  gender=="MALE"
  ) %>% 
  pivot_wider(
  names_from = year_of_birth ,
  values_from = rank
) %>% 
 janitor::clean_names()

```

```{r}
male_2016 =
  filter(
    babynames,
    ethnicity == "WHITE NON HISPANIC",
    year_of_birth == "2016",
    gender == "MALE"
  )

ggplot(male_2016,aes(x=rank, y=count)) + geom_point() + 
  labs(
    title = "Populariy of Male Baby Names among White Non Hispanic Children in 2016",
    x= "Rank in Popularity of Baby Name",
    y="Number of Babies with Name")

```

